// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"基本的なパラメーターを設定するプラグインです。","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"H2A_ES9Checker","status":true,"description":"ES9(ES2018)に未対応ならエラーにする","parameters":{}},
{"name":"H2A_2K_core","status":true,"description":"MV で 2000 する: コア","parameters":{}},
{"name":"H2A_2K_quick","status":true,"description":"MV で 2000 する: 様々な挙動","parameters":{}},
{"name":"AtsumaruAPI","status":true,"description":"","parameters":{}},
{"name":"APIMock","status":true,"description":"","parameters":{}},
{"name":"ModalForm","status":true,"description":"","parameters":{}}
];
